SELECT DATE_FORMAT(A.SALES_DATE, "%Y") AS YEAR, DATE_FORMAT(A.SALES_DATE, "%m") AS MONTH, B.GENDER AS GENDER, COUNT(DISTINCT B.USER_ID) AS USERS
FROM ONLINE_SALE A
JOIN USER_INFO B ON A.USER_ID = B.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER