SELECT A.PRODUCT_CODE, SUM(A.PRICE * B.SA) AS SALES
FROM PRODUCT A
JOIN (SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS SA
    FROM OFFLINE_SALE
    GROUP BY PRODUCT_ID) B ON A.PRODUCT_ID = B.PRODUCT_ID
GROUP BY A.PRODUCT_CODE
ORDER BY SALES DESC, A.PRODUCT_CODE